name: Wplace Background Scanner

on:
  schedule:
    # Runs at minute 42 every 2 hours UTC
    - cron: '42 */4 * * *'

  workflow_dispatch:
    inputs:
      start_x:
        description: 'Start X (Blank = use saved Target)'
        required: false
        type: string
      start_y:
        description: 'Start Y (Blank = use saved Target)'
        required: false
        type: string
      end_x:
        description: 'End X (Blank = use saved Target)'
        required: false
        type: string
      end_y:
        description: 'End Y (Blank = use saved Target)'
        required: false
        type: string
      run_duration_mins:
        description: 'Run duration mins'
        required: false
        type: string
      target_interval:
        description: 'Target Interval (ms)'
        required: false
        type: string
      min_floor:
        description: 'Min Floor (ms)'
        required: false
        type: string
      pause_sec_429:
        description: '429 Pause (s)'
        required: false
        type: string
      penalty_ms_429:
        description: '429 Penalty (+ms)'
        required: false
        type: string
      step_down_ms:
        description: 'Speed Step (-ms)'
        required: false
        type: string
      streak_reqs:
        description: 'Streak for Step'
        required: false
        type: string
      total_cycles:
        description: 'Amount of Cycles'
        required: false
        type: string
      pause_interval_secs:
        description: 'Pause between Cycles (s)'
        required: false
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Execute Scanner
        env:
          # variables without hardcoded defaults
          WORKER_URL: ${{ secrets.WORKER_URL }}
          START_X: ${{ inputs.start_x != '' && inputs.start_x || vars.TARGET_START_X }}
          START_Y: ${{ inputs.start_y != '' && inputs.start_y || vars.TARGET_START_Y }}
          END_X: ${{ inputs.end_x != '' && inputs.end_x || vars.TARGET_END_X }}
          END_Y: ${{ inputs.end_y != '' && inputs.end_y || vars.TARGET_END_Y }}
          # variables with hardcoded defaults
          RUN_DURATION_MINS: ${{ inputs.run_duration_mins != '' && inputs.run_duration_mins || vars.RUN_DURATION_MINS || '67'}}
          PAUSE_INTERVAL_SECS: ${{ inputs.pause_interval_secs != '' && inputs.pause_interval_secs || vars.PAUSE_INTERVAL_SECS || '3' }}
          TOTAL_CYCLES: ${{ inputs.total_cycles != '' && inputs.total_cycles || vars.TOTAL_CYCLES || '1' }}
          TARGET_INTERVAL: ${{ inputs.target_interval != '' && inputs.target_interval || vars.TARGET_INTERVAL || '500' }}
          MIN_FLOOR: ${{ inputs.min_floor != '' && inputs.min_floor || vars.MIN_FLOOR || '399' }}
          PAUSE_SEC_429: ${{ inputs.pause_sec_429 != '' && inputs.pause_sec_429 || vars.PAUSE_SEC_429 || '321' }}
          PENALTY_MS_429: ${{ inputs.penalty_ms_429 != '' && inputs.penalty_ms_429 || vars.PENALTY_MS_429 || '500' }}
          STEP_DOWN_MS: ${{ inputs.step_down_ms != '' && inputs.step_down_ms || vars.STEP_DOWN_MS || '21' }}
          STREAK_REQS: ${{ inputs.streak_reqs != '' && inputs.streak_reqs || vars.STREAK_REQS || '42' }}
          FLUSH_INTERVAL: ${{ vars.FLUSH_INTERVAL || '1000' }}
        run: node bot.js